// The authentication seam (ADR-003): SRP sign-in plus Cognito's native
// SOFTWARE_TOKEN_MFA challenge. Cognito owns the entire MFA lifecycle — we render
// the inputs and pass the code through. No Cognito type crosses this boundary, so
// the library stays replaceable behind these plain functions.
import {
  AuthenticationDetails,
  CognitoUser,
  CognitoUserPool,
  type ICognitoStorage,
} from "amazon-cognito-identity-js";
import { getConfig } from "./config";

export type SignInResult =
  | { status: "MFA_REQUIRED" } // TOTP already enrolled — ask for the code
  | { status: "MFA_SETUP"; secret: string; otpauthUri: string } // first-time enrollment
  | { status: "AUTHENTICATED"; jwt: string };

// The secret is generated by Cognito and shown to the owner; it never leaves the
// browser except into their authenticator via this URI or a manual paste.
function buildOtpauthUri(email: string, secret: string): string {
  return `otpauth://totp/KyleOS:${email}?secret=${secret}&issuer=KyleOS&algorithm=SHA1&digits=6&period=30`;
}

// The library persists its session to localStorage by default; an in-memory store
// keeps tokens out of it so a reload forces re-auth (ADR-003).
const memoryStorage: ICognitoStorage = (() => {
  let store: Record<string, string> = {};
  return {
    getItem: (key) => store[key] ?? null,
    setItem: (key, value) => {
      store[key] = value;
    },
    removeItem: (key) => {
      delete store[key];
    },
    clear: () => {
      store = {};
    },
  };
})();

// The user awaiting its TOTP challenge, held between signIn and submitTotp.
let pendingUser: CognitoUser | null = null;

function pool(): CognitoUserPool {
  const { cognitoUserPoolId, cognitoClientId } = getConfig();
  return new CognitoUserPool({
    UserPoolId: cognitoUserPoolId,
    ClientId: cognitoClientId,
    Storage: memoryStorage,
  });
}

/** SRP sign-in. Resolves to the TOTP challenge or, if MFA is off, the ID token. */
export function signIn(email: string, password: string): Promise<SignInResult> {
  const user = new CognitoUser({ Username: email, Pool: pool() });
  const details = new AuthenticationDetails({ Username: email, Password: password });
  return new Promise((resolve, reject) => {
    user.authenticateUser(details, {
      onSuccess: (session) => {
        pendingUser = null;
        resolve({ status: "AUTHENTICATED", jwt: session.getIdToken().getJwtToken() });
      },
      onFailure: (error) => {
        pendingUser = null;
        reject(new Error(error.message || "Sign-in failed."));
      },
      totpRequired: () => {
        pendingUser = user;
        resolve({ status: "MFA_REQUIRED" });
      },
      // No TOTP registered yet: associate a fresh software token and hand its
      // secret back for the owner to enroll (completed by completeMfaSetup).
      mfaSetup: () => {
        pendingUser = user;
        user.associateSoftwareToken({
          associateSecretCode: (secret) => {
            resolve({ status: "MFA_SETUP", secret, otpauthUri: buildOtpauthUri(email, secret) });
          },
          onFailure: (error) => {
            pendingUser = null;
            reject(new Error(error.message || "Could not start authenticator setup."));
          },
        });
      },
    });
  });
}

/** Hand the six-digit code to Cognito for the in-flight sign-in; returns the ID token. */
export function submitTotp(code: string): Promise<{ jwt: string }> {
  const user = pendingUser;
  if (!user) return Promise.reject(new Error("No sign-in is in progress."));
  return new Promise((resolve, reject) => {
    user.sendMFACode(
      code,
      {
        onSuccess: (session) => {
          pendingUser = null;
          resolve({ jwt: session.getIdToken().getJwtToken() });
        },
        onFailure: (error) => reject(new Error(error.message || "That code was not accepted.")),
      },
      "SOFTWARE_TOKEN_MFA",
    );
  });
}

/**
 * Verify the enrollment code, finishing first-time TOTP setup. verifySoftwareToken
 * both verifies the token and answers the MFA_SETUP challenge internally, so its
 * onSuccess delivers the authenticated session directly (confirmed in the library
 * source) — no follow-up call is needed.
 */
export function completeMfaSetup(code: string): Promise<{ jwt: string }> {
  const user = pendingUser;
  if (!user) return Promise.reject(new Error("No sign-in is in progress."));
  return new Promise((resolve, reject) => {
    user.verifySoftwareToken(code, "KyleOS", {
      onSuccess: (session) => {
        pendingUser = null;
        resolve({ jwt: session.getIdToken().getJwtToken() });
      },
      onFailure: (error) => reject(new Error(error.message || "That code was not accepted.")),
    });
  });
}

/** Sign out: drop any in-flight user and wipe the tokens the library cached into
 * the in-memory store, so no signed-out session can be resurrected (ADR-003). */
export function signOut(): void {
  pool().getCurrentUser()?.signOut();
  pendingUser = null;
  memoryStorage.clear?.();
}
